### PR TITLE
Manual Snipe while NecroBot is working

### PR DESCRIPTION
**Pull request by msx752**
new snipe version 
we don't need close bot for manual snipe
i created snipe program for NecroBot [https://github.com/msx752/MSniper](https://github.com/msx752/MSniper)
-program working same protocol pokesiniper2:// also we can change protocol what we need
-running without username password
-integrated with NecroBot (only communicating on SnipeMS.json)
-program can working multiple necrobot and same pokemon location will send all working bot at the same time
-of course without device information 
-**we dont need SnipeAtPokestops=true**

if any question i answer
**(msniper configured necrobot version 0.9.5 and upper)**

### CODE REVIEW

**Comment by msx752** [comment]
i saw in discord channel KimCORDashian which for pokemon snipe.

we can use it for this 
such as "necrosnipe://Rhydon/19.3811222,-99.177922  94% MudSlapFast/Megahorn you have 768s left"
we can parse it

**Comment by tr1p0z** [comment]
I have last version and is saying incompatible version :-1:

**Comment by msx752** [comment]
@tr1p0z because my codes aren't merged yet. wait v0.9.5

**Comment by tr1p0z** [comment]
Okey thanks I wanna test it :dancer:

**Comment by NoxxDev** [comment]
This update forces the snipe
if user doesn't want to use snipe?

**Comment by msx752** [comment]
not forcing , program only checking debug/SnipeMS.json if file exist working and deleting file and waiting next SnipeMS.json

**Comment by tr1p0z** [comment]
Well i should wait to 0.9.5 i cant wait xD

**Pull request merged**
