### PR TITLE
Update UseNearbyPokestopsTask.cs

### PR DESCRIPTION
**Pull request by Capusjon**
Edit to let it search more consistently for Lure Pokemons.

See issue 324

### CODE REVIEW

**Comment by tiggerite** [comment]
Hey, I've added that and much more to https://github.com/NoxxDev/NecroBot/pull/444

**Comment by Capusjon** [comment]
@tiggerite can you elaborate on what you did for the lured Pokemon?

**Comment by Capusjon** [comment]
Closed since tiggerite added the lines + more

**Comment by tiggerite** [comment]
Yep sure, I basically refactored everything so both FarmPokestopsTask and FarmPokestopsGPXTask both call UseNearbyPokestopsTask - and that contains everything (including capturing lures) that FarmPokestopsTask had. It only calls the non-GPX specific parts that FarmPokestopsTask had if GPXPathing is not set, of course (such as moving to the nearest pokestop - we don't want that when following a GPX path).

**Comment by Capusjon** [comment]
Thanks, I'm going to run with your files and see what it gets me.

**Pull request closed without merging**
