### PR TITLE
Fixing gpx-tracking bug

### PR DESCRIPTION
**Pull request by mo0ojava**
## Short Description
The GPX-tracking has been bugged for as long back as 0.7.1. This fixes the issue. See the attached file for an example.

## Fixes:
gpx-robustness
Fixed the long standing bug where GPX-tracking would reset back to the beginning of the gpx-file whenever "Niantic Servers unstable, throttling API Calls" happened. Tested and working now.

### CODE REVIEW

**Comment by mo0ojava** [comment]
Pardon the messy Pull request. I'm new to this GitHub-thing and apparantly VStudio sent all kinds of files... The only updated file should be FarmPokestopsGPXTask.cs. At least that annoying bug seems gone now.

**Comment by mo0ojava** [comment]
Honestly not sure what the.. happened there. Attaching the file just in case that Pull request was entirely worthless. >_>
[FarmPokestopsGPXTask.cs.txt](https://github.com/NoxxDev/NecroBot/files/418784/FarmPokestopsGPXTask.cs.txt)

**Comment by NoxxDev** [comment]
This is the correct commit?

[52dd39c] (https://github.com/NoxxDev/NecroBot/pull/49/commits/52dd39c9c8043cd45987e532e255b67e508f54fc)

**Comment by mo0ojava** [comment]
Yes, that's it.

**Comment by NoxxDev** [comment]
Added @cfe32e79774a1463a3c144750f8cbc1e743596ab

**Comment by eicool** [comment]
So noxxdev, is both fully made know ? ^^ BTW thanks for your hard work ^^

**Pull request closed without merging**
