### PR TITLE
Add delay before attempting CatchLurePokemons to prevent cooldowns

### PR DESCRIPTION
**Pull request by tiggerite**
Also:

Don't call CatchLurePokemon for intermediate pokestops when sniping
Enable sniping when using GPX pathing
Fix typo (NearestDistane => NearestDistance)
Rename FortPokestop to FarmPokestop as that is its function

Signed-off-by: Tigerite <tigerite@gmail.com>

### CODE REVIEW

**Comment by NoxxDev** [comment]
Resolve conflicts

**Comment by mo0ojava** [comment]
Looked at your commit, Tiggerite. Good work there on making the WalkSniper work alongside GPX-routing! That would be ideal of course. Would be great if you could continue that line of thought on top of the current version. Which routing-method are you planning on defaulting to for the navigation to the snipe-target?

The delay before CatchLuredPokemons may or may not work, depending on whether the cooldown really was the culprit or not. Might be worth testing, but as mentioned the current solution works as well.

**Comment by tiggerite** [comment]
Conflicts fixed, phew. What an ordeal that was!

I can confirm the delay definitely makes lures work again, it's been capturing them for me fine with the added lines. It should be the more robust way of doing so, and also ensures lures will be fine for non-GPX as well.

As for the routing method, it's using the same code as in FarmPokestopsGPXTask.cs

**Comment by NoxxDev** [comment]
There is still conflict, probably was raised after this commit 302873a009104438914194f01a3c95c081eae4c1

**Comment by tiggerite** [comment]
There we go, all fixed again.. hopefully that's the last conflict now!

**Pull request merged**
