### PR TITLE
Add Set Destination in websocket feature.

### PR DESCRIPTION
**Pull request by HassenLin**
## Short Description:
Add Set Destination in websocket feature for Visualizer Tool  .

## Fixes (provide links to github issues if you can):
Add PoGo.NecroBot.CLI\WebSocketHandler\SetDestinationHandler.cs
Modify PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs

Online Visualizer Tool : http://hassenlin.byethost12.com/
Source : https://github.com/HassenLin/necrobotvisualizer

### CODE REVIEW

**Comment by jjskuld** [comment]
Please clean up this pull request.  It should not be reverting FeroxRev to an older version than the one we are currently using unless you have a strong reason.

**Comment by jjskuld** [comment]
By the way thank you for this pull. It is a highly requested feature and one that I tried to implement with only partial success.

**Comment by jjskuld** [comment]
One more suggestion.  What do you think of calling this ForceUsePokestop instead of SetDestination?  It looks like this code forces the bot to use a poke stop.

I also have similar code incoming to force moving to a specific latitude/longitude.  This could be confusing if the web socket call was SetDestination.  Was thinking of merging in Lunat1q's implementation of ForceMoveTo from his Catchem fork.

**Comment by HassenLin** [comment]
I use those code more then one week, and it worked fine, It only need modify PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs and add SetDestinationHandler.cs in project.

It will walk to user destination after current pockstop job.

You can use http://hassenlin.byethost12.com/ to test it, the web site 100% form https://github.com/HassenLin/necrobotvisualizer no addition item in it.

Test Step.
Double click any position on google map and wait.

**Comment by samuraitruong** [comment]
My ideal is add a static variable in UseNearByPokestop to let bot check that there is a command to move, then after move, clear that variable. (you also think about it will cancel human walk snipe too.)

**Comment by HassenLin** [comment]
Open new one

**Pull request closed without merging**
