### PR TITLE
[GUI] Add WebUi Client Manager GUI.

### PR DESCRIPTION
**Pull request by NzV**
Allow to install/update/auto-update/uninstall/switch easily web client ui + improvement to my committed PR #847 + Fix return of a broken PokeEase submodule who is no more needed.

screen1
screen2
screen3
screen4
screen5

### CODE REVIEW

**Comment by ntatoo** [comment]
@NzV when i use necrobotvisualizer and necrobotjavanhawk 
its said connecting to bot , and not responding
but when using pokeesee , work as a carm 

i love the idea , but can you fix it bro ?

**Comment by samuraitruong** [comment]
it deosnt work with my pokeease fork because I completely change structure, if you get source from master is is nothing. 

you have to run grunt build then it will restore all the files . 
Source is source, it never use for run without build. should we change to use public folder instead?

**Comment by ntatoo** [comment]
@samuraitruong i think that we should bring the submodule folder back , cuz its easy to config and dont use more data to download the webui

but thats my opinion

**Comment by jjskuld** [comment]
Perhaps we bring the submodule back as the default, but also have others guis download on demand. For now let's get this pull merged in and then we can go back and enhance it.

@samuraitruong Yes, we should change this so that you specify the path to the entry point (the ```index.html```).

**Comment by NzV** [comment]
@samuraitruong i take a look in to your fork, you just need to edit RootDir/GUI/WebUi/Config.json
add your webclient ui and set "HtlmRootPath" to "public" instead of "src", you also need to add your compiled public folder to your git.

**Comment by NzV** [comment]
@ntatoo i think the issue is the same as samuraitruong the "src" folder (in this case "app" folder) don't contains all necessary script, the dev need to provide a "public" version with all required script include.

**Comment by samuraitruong** [comment]
@NzV : I am developer so i know how to make it work, but if normal use see this feature then try to get source with out compiled like my repo it never work. I think we should setup 
- to public folder
- to a online url (my repo automatically deploy to heroku every time i push master)

**Comment by NzV** [comment]
@samuraitruong thx i will work on this

**Pull request merged**
