### PR TITLE
Pokemon level up filter & misc

### PR DESCRIPTION
**Pull request by samuraitruong**
HI @NoxxDev ,

This pull request include few minor things I done in past few day
- Add filter for upgrade setting 
- Refactor code of LevelUpPokemonTask
- Add Pokemon Grades - that is nothing with logic, just for display rarity fo pokemon in log
- Fix "Niantic API throlte...." cause bot walking back to default coords
- Small change in the websocket of human walk snipe to make it work better with pokeease

Truong

### CODE REVIEW

**Comment by jjskuld** [comment]
@samuraitruong You really need to start breaking up your pull requests into separate feature branches and open pulls for those.  It's hard to test a big lump of changes all at once.

**Comment by samuraitruong** [comment]
I not going to do that. Plz cancel my pr. Thanks

Get Outlook for Android<https://aka.ms/ghei36>



On Sat, Sep 3, 2016 at 3:42 PM +1000, "jjskuld" <notifications@github.com<mailto:notifications@github.com>> wrote:


@samuraitruong<https://github.com/samuraitruong> You really need to start breaking up your pull requests into separate feature branches and open pulls for those. It's hard to test a big lump of changes all at once.

**Comment by jjskuld** [comment]
@samuraitruong No need to get salty.  It's just my own personal opinion and not the opinion of @NoxxDev.  Whether or not the pull request is accepted is up to @NoxxDev

**Comment by jjskuld** [comment]
@samuraitruong By the way, I very much respect the work you are doing and I hope that we can continue to make Necrobot better. I just hope that our repositories don't get too out of sync and you continue to send pull requests.

**Comment by samuraitruong** [comment]
well, I understand the rules, but i don't have time to make feature branch for those work that I already done in my develop branch then merge to my master branch. I will add new feature from new branch but not these feature.

**Pull request merged**
