### PR TITLE
Add yours walking strategy as a fallback/alternative for Google walki…

### PR DESCRIPTION
**Pull request by jjskuld**
## Short Description:
1. Add YOURS server walking strategy as an alternative for Google walking.  Does not require an API key.
2. Add multiple fallbacks strategies.
Google fails --> YOURS server --> Default walking (straight-line)

New configuration:
```
  "YoursWalkConfig": {
    "UseYoursWalk": true,
    "YoursWalkHeuristic": "bicycle",
    "YoursServerUrl": "http://www.yournavigation.org/api/dev/route.php"
  },
```

By default you don't have to change it and it will use the public server at yournavigation.org.
But if you are technically inclined, you can run your own YOURS server.

See:
http://wiki.openstreetmap.org/wiki/YOURS

This is good if you hit the limits of your Google API key, it will fall back to Yours navigation, and then if that server is overloaded or not responding, then it falls back to the default walking strategy.

### CODE REVIEW

**Comment by NoxxDev** [comment]
Check conflicts

**Comment by jjskuld** [comment]
Ok fixed the conflicts.

**Comment by NoxxDev** [comment]
There's only one problem, yournavigation.org does not support many requests, causing a ddos

**Comment by jjskuld** [comment]
In that case, what about disabling it by default but still allowing people to run their own YOURS server?

**Comment by jjskuld** [comment]
Ok, I've refactored so that YOUR server is disabled by default.  You now have several options for YOURS servers:

1) Yournavigation.org - http://www.yournavigation.org/api/dev/route.php
2) MobRouting - http://mobrouting.com/api/dev/gosmore.php
3) Custom server (running off your own localhost)

**Comment by NoxxDev** [comment]
Check conflicts after #437 and #435

**Comment by jjskuld** [comment]
Refactored again.  With my changes, all the routing enhancements that were applied to the Google walking strategy can be applied to other strategies since I've moved most of the walking logic into a ```BaseWalkStrategy``` class. Now it doesn't matter where you get the coordinates from (Google, YOURS, etc.), but the walking logic is shared.

Here is walking using YOURS navigation server.
screen shot 2016-08-23 at 9 18 30 am

**Pull request merged**
