### PR TITLE
MSniper 'Did not find a Pokemon error' solution

### PR DESCRIPTION
**Pull request by msx752**
bug fixed,
now exactly working what we need
reference issue https://github.com/NoxxDev/NecroBot/issues/808

### CODE REVIEW

**Comment by iwean** [comment]
@msx752 
I'm build from this latest branch.... than I got this from your commit:
...
screenshot_168

**Comment by iwean** [comment]
I'm tested manual snipe from pokezz & pogolocfeeder... get the same error

**Comment by msx752** [comment]
wrong version, how you compiled ? :)

**Comment by iwean** [comment]
@msx752 
Hmm... I'm updating to 1.0.5 .... than I get register command every I click link on feeder site.
....
screenshot_169

**Comment by msx752** [comment]
@iwean  method 1: delete everything (temp folder/bat files ect..) in msniper's folder except msniper.exe (v1.0.5)
run again. also if you changed your msniper folder, you should run registerprotocol.bat 

methods2: 
- close all bot
- if you open visual studio close it(necrobot project),
- run as administartor to msniper.exe

**Comment by iwean** [comment]
Ok @msx752 thx a lot... work like a charm now.
After kill visual studio and rerun the bot :+1: 
You are Awesome !!!
....
screenshot_170

**Pull request merged**
