### PR TITLE
Human walk snipe bug fixes + enhancement

### PR DESCRIPTION
**Pull request by samuraitruong**
Just realized we got some fake softban message because try to fort same pokedesktop.  not sure who make the code change but seem they didn't merge properly. I corrected in this pull request. Also added new support for configurate delay when reach destination as request  https://github.com/NoxxDev/NecroBot/issues/642

### CODE REVIEW

**Comment by iwean** [comment]
I just tought it was fake softban.... because when I reload your bot, there's no sofban.

**Comment by samuraitruong** [comment]
yes it was fake, because we spin same pokestop twice

**Comment by iwean** [comment]
Btw @samuraitruong can I test this fix version? Where can I download?

**Comment by iwean** [comment]
How about `checking` other than `wait` ..... value for the string `HumanWalkSnipeDestinationReached` ?

When you reach location... you will check, not just wait :)

**Comment by samuraitruong** [comment]
before, i hard code wait 2 sec, now it will wait base on config

**Comment by iwean** [comment]
Oh ok... so we can set it on config. :+1:

**Comment by mo0ojava** [comment]
I have a faint memory of @NoxxDev fixing the fake softban in an earlier commit. Have you checked that, @samuraitruong? (9bd903a1bb3565409beb8c6aee0f6900686a85c9)

**Comment by NoxxDev** [comment]
Contain errors, shows you found 0 and will capture

**Comment by samuraitruong** [comment]
weird, I haven't seen that issue. maybe check your filters, can you include zubat in the list and see how it display.

**Comment by samuraitruong** [comment]
hum, look weird to  me, even i use my local build but it not work like the one i have at home. 

Please hold on on this PR. I will investigate later tonight

**Comment by samuraitruong** [comment]
@NoxxDev  : sorry, it is none issue, my config issue only.

please turn on pokeradar & skipllaged source in config then it will work for you.

 "HumanWalkSnipeConfig": {
    "DisplayPokemonList": true,
    "MaxDistance": 1500.0,
    "MaxEstimateTime": 900.0,
    "CatchEmAllMinBalls": 50,
    "TryCatchEmAll": true,
    "CatchPokemonWhileWalking": true,
    "SpinWhileWalking": true,
    "AlwaysWalkback": false,
    "SnipingScanOffset": 0.025,
    "Enable": true,
    "WalkbackDistanceLimit": 350.0,
    "IncludeDefaultLocation": true,
    **"UsePokeRadar": true,
    "UseSkiplagged": true,**
    "UseSnipePokemonList": true,
    "MaxSpeedUpSpeed": 0.0,
    "AllowSpeedUp": false,
    "DelayTimeAtDestination": 3000
  },

**Comment by NoxxDev** [comment]
enabled 

the error is still the same as the image

**Comment by samuraitruong** [comment]
what is your speed . if speed is too low you never reach pokemon. then that list will be filter out. before I just display everything that match with filter and not consider about distance. 

can you make your speed higher 40km/h and retest the same config.

**Comment by samuraitruong** [comment]
I am running very good here - 

[11:38:04] (HUMAN WALK) Found 12 pokemon matched with you filters. Human walking sniper won't catch em all. but try to maximun catch if possible.
[11:38:04]      Source      |  Name               |    Distance    |   Expires        |  Travel times   | Catchable
[11:38:04]  Pokeradar        |  Magmar            |  897.74m  	|  02 min 17 sec  |  02 min 32 sec  | Possible
[11:38:04]  Pokeradar        |  Clefable          |  1560.74m  	|  07 min 06 sec  |  02 min 28 sec  | Possible
[11:38:04]  Pokeradar        |  Kangaskhan        |  580.00m  	|  01 min 51 sec  |  01 min 05 sec  | Possible
[11:38:04]  Pokeradar        |  Kangaskhan        |  1432.30m  	|  04 min 12 sec  |  02 min 17 sec  | Possible
[11:38:04]  Pokeradar        |  Golbat            |  538.67m  	|  02 min 58 sec  |  01 min 01 sec  | Possible
[11:38:04]  Pokeradar        |  Magikarp          |  497.54m  	|  01 min 23 sec  |  01 min 57 sec  | Possible
[11:38:04]  Pokeradar        |  Magikarp          |  966.45m  	|  03 min 38 sec  |  02 min 38 sec  | Possible
[11:38:04]  Pokeradar        |  Eevee             |  972.36m  	|  13 min 21 sec  |  02 min 38 sec  | Possible
[11:38:04]  Pokeradar        |  Eevee             |  984.34m  	|  03 min 05 sec  |  02 min 39 sec  | Possible
[11:38:04]  Pokeradar        |  Eevee             |  1075.15m  	|  06 min 30 sec  |  02 min 47 sec  | Possible
[11:38:04]  Pokeradar        |  Eevee             |  1165.99m  	|  02 min 27 sec  |  02 min 55 sec  | Possible
[11:38:04]  Pokeradar        |  Eevee             |  1208.80m  	|  06 min 49 sec  |  02 min 58 sec  | Possible
[11:38:04] (HUMAN WALK) Found Magmar spawning | lat: -37.8116543568025, lng: 144.975080638938, dist 897.74m , expired in 02 min 18 sec | Estimate : 01 min 31 sec | Allow spin: Yes | Allow catch : No | Speed 42.16km/h
[11:39:22] (HUMAN WALK) destination reached | lat: -37.8116543568025, lng: 144.975080638938 | wait :0.00 sec
[11:39:22] Looking for Pokemon...
[11:39:24] (Threw ball) Nice hit. Curve-ball...
[11:39:26] (CatchSuccess) | (Normal) Magmar Lvl: 1 CP: (29/32) IV: 41.00% | Chance: 100% | 0.00m dist | with a PokeBall (214 left). | 120 EXP earned | Candies: 74 | lat: -37.811654 long: 144.975081
[11:39:26] (HUMAN WALK) Encountered Magmar  | lat :-37.8116543568025 , Lng : 144.975080638938 | removed from snipping list
[11:39:33] Used Razz Berry | 36 remaining
[11:39:33] (Threw ball) Great hit. Straight-ball...
[11:39:33] (CatchMissed) | (Normal) Charmander Lvl: 15 CP: (350/409) IV: 38.00% | Chance: 15.46% | 21.05m dist | with a GreatBall (54 left). | lat: -37.811786 long: 144.975253
[11:39:36] Used Razz Berry | 35 remaining
[11:39:36] (Threw ball) Great hit. Straight-ball...
[11:39:37] (CatchFlee Attempt #2) | (Normal) Charmander Lvl: 15 CP: (350/409) IV: 38.00% | Chance: 15.46% | 21.05m dist | with a GreatBall (53 left). | lat: -37.811786 long: 144.975253
[11:39:40] Looking for incense Pokemon...
[11:39:41] (HUMAN WALK) Found Eevee spawning | lat: -37.812472447932, lng: 144.978781173713, dist 337.86m , expired in 05 min 54 sec | Estimate : 00 min 43 sec | Allow spin: Yes | Allow catch : Yes | Speed 42.16km/h
[11:39:41] Looking for Pokemon...
[11:40:01] (Threw ball) Great hit. Curve-ball...
[11:40:03] (CatchSuccess) | (Normal) NidoranFemale Lvl: 4 CP: (74/91) IV: 20.00% | Chance: 78.21% | 67.54m dist | with a PokeBall (213 left). | 160 EXP earned | Candies: 252 | lat: -37.812779 long: 144.977318
[11:40:09] (HUMAN WALK) destination reached | lat: -37.812472447932, lng: 144.978781173713 | wait :0.00 sec
[11:40:09] Looking for Pokemon...
[11:40:11] Used Razz Berry | 34 remaining
[11:40:11] (Threw ball) Nice hit. Curve-ball...
[11:40:13] (CatchSuccess) | (Normal) Eevee Lvl: 23 CP: (568/707) IV: 9.00% | Chance: 24.97% | 0.00m dist | with a GreatBall (52 left). | 120 EXP earned | Candies: 236 | lat: -37.812472 long: 144.978781
[11:40:13] (HUMAN WALK) Encountered Eevee  | lat :-37.812472447932 , Lng : 144.978781173713 | removed from snipping list
[11:40:19] (Threw ball) Ordinary hit. Curve-ball...
[11:40:20] (CatchSuccess) | (Normal) Kangaskhan Lvl: 4 CP: (205/213) IV: 75.00% | Chance: 31.28% | 13.66m dist | with a PokeBall (212 left). | 110 EXP earned | Candies: 131 | lat: -37.812370 long: 144.978695
[11:40:24] Looking for incense Pokemon...
[11:40:24] (HUMAN WALK) Found Eevee spawning | lat: -37.8139177740375, lng: 144.978522991589, dist 162.45m , expired in 11 min 02 sec | Estimate : 00 min 28 sec | Allow spin: Yes | Allow catch : Yes | Speed 42.16km/h
[11:40:25] Looking for Pokemon...
[11:40:38] (HUMAN WALK) destination reached | lat: -37.8139177740375, lng: 144.978522991589 | wait :0.00 sec
[11:40:38] Looking for Pokemon...
[11:40:39] Used Razz Berry | 33 remaining
[11:40:39] (Threw ball) Great hit. Curve-ball...
[11:40:41] (CatchSuccess) | (Normal) Eevee Lvl: 22 CP: (565/677) IV: 23.00% | Chance: 25.54% | 0.00m dist | with a GreatBall (51 left). | 160 EXP earned | Candies: 239 | lat: -37.813918 long: 144.978523
[11:40:41] (HUMAN WALK) Encountered Eevee  | lat :-37.8139177740375 , Lng : 144.978522991589 | removed from snipping list
[11:40:48] (Threw ball) Ordinary hit. Curve-ball...
[11:40:49] (CatchMissed) | (Normal) Zubat Lvl: 4 CP: (61/67) IV: 66.00% | Chance: 78.21% | 52.54m dist | with a PokeBall (211 left). | lat: -37.813451 long: 144.978437
[11:40:52] (Threw ball) Great hit. Straight-ball...
[11:40:53] (CatchSuccess Attempt #2) | (Normal) Zubat Lvl: 4 CP: (61/67) IV: 66.00% | Chance: 78.21% | 52.54m dist | with a PokeBall (210 left). | 150 EXP earned | Candies: 2034 | lat: -37.813451 long: 144.978437
[11:41:00] Used Razz Berry | 32 remaining
[11:41:00] (Threw ball) Excellent hit. Straight-ball...
[11:41:01] (CatchSuccess) | (Normal) Clefairy Lvl: 11 CP: (327/377) IV: 35.00% | Chance: 27.08% | 55.50m dist | with a GreatBall (50 left). | 200 EXP earned | Candies: 292 | lat: -37.814283 long: 144.978093
[11:41:07] (Threw ball) Nice hit. Curve-ball...
[11:41:08] (CatchSuccess) | (Normal) Staryu Lvl: 23 CP: (551/616) IV: 56.00% | Chance: 31.22% | 55.50m dist | with a PokeBall (209 left). | 120 EXP earned | Candies: 401 | lat: -37.813553 long: 144.978953
[11:41:10] Looking for incense Pokemon...
[11:41:11] (HUMAN WALK) Found Eevee spawning | lat: -37.8135385090416, lng: 144.98127697506, dist 245.78m , expired in 04 min 43 sec | Estimate : 00 min 35 sec | Allow spin: Yes | Allow catch : Yes | Speed 42.16km/h
[11:41:11] Looking for Pokemon...
[11:41:12] (Threw ball) Nice hit. Curve-ball...
[11:41:14] (CatchSuccess) | (Normal) Eevee Lvl: 12 CP: (321/369) IV: 40.00% | Chance: 34.57% | 64.13m dist | with a PokeBall (208 left). | 120 EXP earned | Candies: 242 | lat: -37.813494 long: 144.979211
[11:41:18] Looking for Pokemon...
[11:41:31] (HUMAN WALK) destination reached | lat: -37.8135385090416, lng: 144.98127697506 | wait :0.00 sec

**Comment by iwean** [comment]
@samuraitruong Can you give another string to "Individual filter catch", so ir can be enabel or disable.

Maybe like "Enable": true, ....like on main config HMW but specific per individual filter.

Thx in advance...

**Comment by samuraitruong** [comment]
Do we need this. You can set priority to 100 as hack

Get Outlook for Android<https://aka.ms/ghei36>



On Mon, Aug 29, 2016 at 6:54 PM +1000, "Iwan Novirion" <notifications@github.com<mailto:notifications@github.com>> wrote:


@samuraitruong<https://github.com/samuraitruong> Can you give another string to "Individual filter catch", so ir can be enabel or disable.

Maybe like "Enable": true, ....like on main config HMW but specific per individual filter.

Thx in advance...

**Comment by iwean** [comment]
Oh I see.... ok I'll set 100 for it :+1:

**Pull request merged**
