### PR TITLE
ResumeTrack/Seg/Pt initialization for GPX and "API throttling", to prevent long jumps when pathing, and refactoring of code to ensure PokeStopListEvent always sends the full list of nearby stops when using GPX

### PR DESCRIPTION
**Pull request by tiggerite**
Although I have added three new values to LocationConfig, they are not stored in the configuration thanks to JsonIgnore (they are calculated on-the-fly and not needed there), so they don't need to be documented. 

I have made two changes in this pull request as FarmPokestopsGPXTask is affected in both, the primary one is the ResumeTrack/Seg/Pt fixes. However, using PokeEase with GPX generates lots of errors without the PokeStopListEvent fix, so I included that also as it is becoming ever more popular as a GUI for NecroBot.

### CODE REVIEW

**Comment by morrrido** [comment]
You use GPX pathing? Don't you have this issue https://github.com/NoxxDev/NecroBot/issues/324 ?

**Comment by tiggerite** [comment]
@morrido, I hadn't actually noticed that bug. I will add the LureInfo check to the code after the if tomorrow and make another pull request.

**Comment by tiggerite** [comment]
I mean @morrrido sorry. iPhone autocorrect!

**Comment by tiggerite** [comment]
@morrrido I have now committed another pull request, so that both FarmPokestopsTask and FarmPokestopsGPXTask use consistent logic. This has the added benefit of not only checking for lured pokemon, but also ensuring we do not get a soft ban for spinning too many stops over 24 hours and adds randomization.

**Comment by morrrido** [comment]
Thank you @tiggerite

**Pull request merged**
