### PR TITLE
Secondary PR for supporting new POGOProtos. (https://github.com/NoxxDev/NecroBot-Rocket-API/pull/10)

### PR DESCRIPTION
**Pull request by aididhaiqal**
This PR add support for latest POGOProtos by AEONLucic (Which fix a lot thing),Since a few change happend to the protos.This PR is required to support them.There is one more PR (https://github.com/NoxxDev/NecroBot-Rocket-API/pull/10) which fix the signature generation for the new protos

### CODE REVIEW

**Comment by NoxxDev** [comment]
Had already checked the latest commits to POGOProtos based AEONLucic, but the following error occurs that I haven't found a solution to fix:

`(ATTENTION) On PokeStops usable found in your area. Is your maximum distance too small?`

**Comment by aididhaiqal** [comment]
Isn't that error mean it could not find any pokestop?

**Comment by NoxxDev** [comment]
@aididhaiqal yes, not find pokestops

**Comment by aididhaiqal** [comment]
I guess,If no pokestop not found.We should have bot in idle mode or make it follow road path

**Comment by NoxxDev** [comment]
@aididhaiqal 
Is a configuration error in RequestBuild
The bot won't find any pokestop or pokemon

**Comment by aididhaiqal** [comment]
@NoxxDev I want to send a packet name SetBuddyPokemon,How can i do this?

**Pull request closed without merging**
