### PR TITLE
Add Google and MapQuest elevation service to get elevation every time bot moves

### PR DESCRIPTION
**Pull request by jjskuld**
## Short Description:
For increase ban safety, we are now getting the elevation for a geo coordinate from Google Elevation Service and/or MapQuest Elevation Service:

1) At startup time for default location
2) Every time the bot moves
3) Every time the bot teleports to new location for sniping.

If a Google API Key is present, then it will use the Google service.
If not present, then it will use the MapQuest service (no key required since it's using the MapQuest demo key).

This is totally transparent to the user.

Elevation values are smartly cached in a LRU cache.  We cache the latitude and longitude only up to 3 decimal place precision, which corresponds to locations in the same neighborhood.  This ensures that we don't hit the MapQuest service to often since we are doing the check every time the bot moves.  

For most average setups, the MapQuest service will only be hit once on startup and never again since the altitude should be the same when botting within the same area.

If you are sniping, it will probably hit the web services each time you jump out to a new location.

### CODE REVIEW

**Comment by LordDeimos666** [comment]
Why use an hardcoded apikey?

**Comment by alexthepink95** [comment]
i might be wrong but ur getting true elevation not altitude

**Comment by WoolF911** [comment]
Or Mapzen API

**Comment by jjskuld** [comment]
@LordDeimos666 It's using the public demo key from the MapQuest site.  We could make that configurable easily if desired.  It would mean that you would have to go sign up for a key yourself.  Maybe this is the best so that people that don't want to use the public key can use their own key.

@alexthepink95 Hm.. I was not really all that aware of the distinction between the two. But you may be right.  Let me research this a bit.  If it's the wrong value, we can probably do a conversion pretty easily.

**Comment by jjskuld** [comment]
"Altitude is a measurement used to show how far off the ground you are, elevation is used to show how high above sea level you are."  Got it.  Stay tuned...

**Comment by jjskuld** [comment]
I think I will also go ahead and implement this altitude check with support for Google's Elevation service as well.  So similar to the walk logic, you can now start with Google's service, then if you exceed the API limits, it can fall back to the MapQuest one.

Both MapQuest and Google's Elevation services, both are returning "elevation".  I checked and they both return the same elevation values for a coordinate.  So now the question is, what does the PokemonGo server want, altitude or elevation?

**Comment by jjskuld** [comment]
Ok, I think the phone sensors are all estimating elevation using GPS (unless you have a new iPhone 6 with barometer that can calculate elevation without GPS).  So the value that is being retrieved from MapQuest is indeed correct.

**Comment by joe1chen** [comment]
Some extra pokeball caching logic I was testing snuck into the pull request.  I will remove this code and re-do the pull request shortly.

**Comment by jjskuld** [comment]
Some pokeball caching code I was testing snuck into the code by accident.  This should not be there. I will clean this up and redo the pull request.

**Comment by NoxxDev** [comment]
what I looked at, user would be forced to use an api key?

**Comment by jjskuld** [comment]
To be clear no key is required.
1. If you have google key for walk, it will use that key to enable elevation from Google.
2. Otherwise it falls back on mapquest service, which is hard coded to use the mapquest demo key on their website (no limitations on this key)

**Pull request merged**
