### PR TITLE
Add default GUI (integrated with PokeEase)

### PR DESCRIPTION
**Pull request by jjskuld**
## Short Description:
Integrates with PokeEase to provide a default GUI for the bot.  You can now run NecroBot.GUI.exe to start up the GUI.  At the moment the GUI is not a standalone application (you still need to run the CLI).  But in subsequent revisions, I will merge the CLI and the GUI so that the GUI will be standalone.

The GUI is provided by PokeEase.  So why NecroBot.GUI then?
1. It provides a default UI without having to download external dependency.
2. It is a running inside a .NET WPF app with Awesomium (Chrome engine) hosting the browser window, so it will eventually allow us to get rid of the standalone CLI and just have a standalone GUI app.

necrobot gui

We can still keep the CLI around, but for those of you that are like me and prefer the GUI, then this is going to be a slick integration.

## Future Enhancements
1. Make GUI app standalone.
2. Integrate with settings

## Credits:
PokeEase - https://github.com/GediminasMasaitis/PokeEase

### CODE REVIEW

**Comment by NoxxDev** [comment]
Check conflicts

**Comment by NoxxDev** [comment]
Fix errors and references missing

**Comment by dhea252** [comment]
account banned -_-

**Comment by dhea252** [comment]
[gejala stroke](http://gejalastroke.tasikstore.com) ringan dan cara menanganinya secara alami harus diperhatikan selalu secara serius , karena saat ini kasus penyakit stroke banyak terjadi dikalangan masyarakat dari mulai stroke ringan hingga stroke berat. 
Meski yang dialami masih gejala stroke ringan tapi penanganannya harus secara tepat karena bisa berakibat fatal jika tidak diatasi dengan obat stroke yang ampuh. Sebelum kita membahas lebih lanjut mengenai pengobatan stroke, maka kita harus mempelajari dulu tentang apa itu penyakit stroke, penyebab penyakit stroke, gejala stroke, 
serta bahaya apa yang bisa muncul? Setelah itu baru kita bisa memilih obat stroke yang tepat yang akan kita gunakan.

**Comment by jjskuld** [comment]
@NoxxDev Sorry about the missing references. I had installed the Awesomium package via their installer.  Instead of relying on developers to have to do this, I'll add the NuGet package.  Stay tuned.

**Comment by jjskuld** [comment]
Ok, try again. It should compile without having the SDK installed now.

**Comment by bulubebek** [comment]
It would be awesome if you can add CLI output to pokease interface. Put player info on top of windows, and put CLI output on the bottom of window. Both can be hide and shown by a single click. :)

**Comment by jjskuld** [comment]
@bulubebek Funny you should ask that.. I was just adding it this morning. About 75% done...

**Comment by bulubebek** [comment]
@jjskuld coincidence? very nice.. :smile:  keep up your good job man!

**Comment by jjskuld** [comment]
@bulubebek Player info on top... that's a good idea.. I was trying to figure out the best place to put the button that opens the CLI. Will finish it up in the morning

**Comment by iwean** [comment]
@jjskuld Can you share it for the test? Can't wait for the release :smiley:

**Comment by samuraitruong** [comment]
https://github.com/samuraitruong/pokeease

I forked that i add feature for human snipe

**Comment by iwean** [comment]
Thx a lot @samuraitruong :+1: 
....
screenshot_156

**Comment by samuraitruong** [comment]
yeah, I added human walk snipe to my code too. 

image

**Comment by iwean** [comment]
Aww...!!! Just click and catch? Awesome mate !!! :+1:  :+1:

**Comment by jjskuld** [comment]
@samuraitruong Perfect, will merge in your branch.

**Comment by samuraitruong** [comment]
image

**Comment by jjskuld** [comment]
With console logging added:
pokeease-console

**Comment by bulubebek** [comment]
great job mate! cant wait for its release.. :)

**Comment by NoxxDev** [comment]
Good PR, I will check

**Comment by NoxxDev** [comment]
Bug not work scroll


Bug Automatic select GUI and


Bug Overlapped

**Comment by joe1chen** [comment]
I fixed the overlapped arrow which was directly related to the work I did.   Will look at the other issues tomorrow.

**Comment by LightDestory** [comment]
Hi, I have a question:
The GUI will handle also the first start setup?

**Comment by Capusjon** [comment]
So how do I add this gui now?

**Pull request merged**
