### PR TITLE
Google Walk Improved

### PR DESCRIPTION
**Pull request by Trankilis**
* Google Walk with Directions Service
* Direction Service with Cache.  If bot go to Pokestop that already visited, cache can save some requests.
* Removed need to GoogleApi. Without it Google has quota of 2500 requests per IP.
* Created Strategies to Walk, to reduce code complexity and better manutenability
* Created new session for Google Settings
* New folder with all settings, one file per class

### CODE REVIEW

**Comment by mo0ojava** [comment]
Ouch - splitting the settings into a myriad of small files?! This will potentially become very cumbersome to work with. You'd need a very good cause to motivate such a move in my opinion. What would that be...?

**Comment by FaruqX** [comment]
screenshot_77

i think more humanize if walk not at same path?

**Comment by ComputerApp1234** [comment]
Is the bot now sending an altitude ?

**Comment by bulubebek** [comment]
@Trankilis +1 .. keep up your good work man!
@FaruqX I know your location.. banjarbaru.. museum lambung mangkurat. :smile: 
@ComputerApp1234 answered on #177

**Pull request merged**
