### PR TITLE
Added pokemon catch count, pokestop visit count and sniper snipe coun…

### PR DESCRIPTION
**Pull request by damuao**
## Short Description:

Added pokemon catch count, pokestop visit count and sniper snipe count to prevent being softbanned.

Options added:
Under "PokemonSettings": 
    "SnipeRestSeconds": 660, (Will stop sniping for this amount of seconds once SnipeCountLimit is reached)
    "SnipeCountLimit": 39, (Rest after sniping this amount of pokemons)
    "CatchPokemonLimit": 999, (Will not catch more than this amount of pokemons for the duration of CatchPokemonLimitMinutes)
    "CatchPokemonLimitMinutes": 1470,
    "PokeStopLimit": 1998, (Will not visit more than this amount of pokestops for the duration of PokeStopLimitMinutes)
    "PokeStopLimitMinutes": 1470,

## Fixes:

No longer thrash SSDs. Will only save location upon exit instead of doing so every time player moves.

### CODE REVIEW

**Comment by iwean** [comment]
Sound great! (y)

**Comment by vipery** [comment]
And "No pokemons found to snipe count" need too. Easy get softban, if poke site lagged. Spam 10 min to snipe = softban >>> hardban.

**Comment by NoxxDev** [comment]
19 errors on compile

**Comment by Cranki** [comment]
Could you also add that the Bot continues moving if he archives KillswitchCatch but KillSwitchPokestops not? And the other way around to...
So if KillsSwitchCat is 40/40, and t KillSwitchPokestops 40/70 that he continues until both Killswitches archives their limits?

**Comment by damuao** [comment]
Will submit a new one

**Pull request closed without merging**
