### PR TITLE
[GUI] Remove submodule PokeEase (Autodownloaded now)

### PR DESCRIPTION
**Pull request by NzV**
-Remove sub module PokeEase
-PokeEase is now download from GitHub (master branch) when the gui
start.
-Support for multi GitHub repository.
-Add an auto-update features for PokeEase based on the last commit hash
(optional).

I don't have add any gui during the download of PokeEase so it will have some delay before the application showed up.

WorkingDir/GUI/Config/WebUiClient.json:

{
  "AutoUpdateWebUiClient": false,
  "CurrentWebUiClient": "PokeEase Official",
  "WebUiClients": {
    "PokeEase Official": {
      "RepoOwner": "GediminasMasaitis",
      "RepoName": "PokeEase",
      "HtlmPath": "src"
    },
    "PokeEase Fork By jjskuld": {
      "RepoOwner": "jjskuld",
      "RepoName": "PokeEase",
      "HtlmPath": "src"
    }
  }
}

### CODE REVIEW

**Comment by jjskuld** [comment]
This looks pretty nice.  Thanks for cleaning up this code.  Will have a chance to test this in a few hours but eyeballing changes looks good.

As a side note, is there any interest in supporting more than one gui?  
I'm thinking of https://github.com/nicoschmitt/necrobotvisualizer
I haven't had a chance to add the console to that ui but it might be nice to be able to switch between ui's.

**Comment by ntatoo** [comment]
@jjskuld i try to implate the https://github.com/nicoschmitt/necrobotvisualizer to source
but i only can build the build pack , not merge with the source of necro 
*sorry for my bad english

**Comment by Ev0luti0n2016** [comment]
I did not have a GUI either and open the program with Chrome since it does not work correctly with another browser.

Using this link opens it up in any browser and I have had no issues:
   http://hassenlin.byethost12.com/

@jjskuld  - Thanks for working on PokeEase...I do enjoy it very much :)

**Comment by samuraitruong** [comment]
well, I added many feature on pokeease to my fork. we need to merge after all.

**Comment by mo0ojava** [comment]
I've been using this for a good while and prefer it to PokeEase tbh. 
https://github.com/AndikaTanpaH/NecrobotJavanHawk
I think it's a fork from Nico but with more details.

**Comment by jjskuld** [comment]
This looks good. I think the only improvement would be to add some feedback the first time around, perhaps load a temporary html page with a spinner and loading message and then load the real page once it has been downloaded. We can add this later.

**Pull request merged**
