### PR TITLE
Gui updates

### PR DESCRIPTION
**Pull request by jjskuld**
## Short Description:
GUI Updates:
1) Updated Awesomium browser to better support PokeEase
2) Integrated Human Snipe UI from https://github.com/samuraitruong/PokeEase

See the new human snipe UI on left:
human snipe

### CODE REVIEW

**Comment by ntatoo** [comment]
@jjskuld i try to test the code and got this eror
untitled

**Comment by jjskuld** [comment]
@ntatoo You're right.. one sec while I add the binaries.

**Comment by iwean** [comment]
Not yet implement string command "\t " on HighestsPokemoCell for the console...
....
screenshot_173

**Comment by iwean** [comment]
And where's my sniping icon?
...
screenshot_172

**Comment by ntatoo** [comment]
@iwean bro download submodule nya di https://github.com/samuraitruong/PokeEase
jangan di submodule dari noxdev nya

**Comment by iwean** [comment]
Owalah... oke bro @ntatoo ... thx :+1:

**Comment by ntatoo** [comment]
@iwean siap bro , soalnya di ane aman" aja sih , hahaha
oh ya , salam gue anak riau

**Comment by iwean** [comment]
Hah serius? Riau dimana? Gw di Bengkalis

**Comment by mo0ojava** [comment]
Agree with @ntatoo. There's some post-build xcopy-ing going on that raises an error when compiling. For some reason you are assuming that there's a \PokeEase\src-folder and then proceed to copy that to a html-folder under PoGo.NecroBot.GUI.

@jjskuld Why is this? From what I can see the PokeEase-code submodule reside in PoGo.NecroBot.GUI.

I usually just remove the xcopy from post-build settings before compiling. Would be great if you could remove that (or fix the error) so that we can compile without doing hands-on.

**Comment by ntatoo** [comment]
@iwean ane di pekanbaru bro

@mo0ojava for now just download from https://github.com/samuraitruong/PokeEase
maybe he will fix it in the next merge

**Comment by jjskuld** [comment]
The PokeEase git sub module is pulled in to the root folder after you initialize submodules.

If you are missing this submodule then you did not run the git submodule initialization before compiling.

git submodule update --init --recursive

The version of PokeEase that I am pulling in as a submodule is from https://github.com/jjskuld/PokeEase
If you want to test both snipe and console changes together use this one.

**Pull request merged**
