### PR TITLE
First Start More 2

### PR DESCRIPTION
**Pull request by LightDestory**
New configurations:
- Desired Nickname (AutoComplete tutorial)
- Walking Speed Settings
- Websocket

I JUST want to warn: I can't compile due to some error with #712

### CODE REVIEW

**Comment by hardknoxni69a** [comment]
Would an option to choose team be possible to implement as well? Or no because requires gym

**Comment by iwean** [comment]
@LightDestory I make fresh PTC account from Niantic pogo site.... than run it on the bot to lvl 20, but never login it on the phone.
So how about my account if I activate AutoComplete Tutorial?

**Comment by LightDestory** [comment]
@iwean  As I said AutoComplete Tutorial Feature isn't mine. But, as you can read on #690 , this feature is usefull to select random gender,  default clothing and nickname (on config.json you can configure only a desired nickname tho)
If you account is lvl 20, this feature is useless for you. Gender and Clothing can't be changed. But Niantic added a rename account that can be used only once.
I think that AutoComplete Tutorial is usefull for new account (because you will not waste the "rename" starting with a desired nickname).

**Comment by iwean** [comment]
@LightDestory Ok thank's for your explanation. That's what I concern... to not waste the "rename".
Once again... thank's :+1:

**Pull request merged**
