### PR TITLE
New Feature human walk snipe

### PR DESCRIPTION
**Pull request by samuraitruong**
Hi, 
I would like to ask you merge this PR . basically it allow bot fetch data from skiplagged and pokeradar to find local rare pokemon (in your filter list) and walk to catch them. you can see our test & discussion here.

https://github.com/NoxxDev/NecroBot/issues/398

Thanks

### CODE REVIEW

**Comment by NoxxDev** [comment]
@samuraitruong 
Good PR, but need to document the new settings for the wiki

"HumanWalkSnipeConfig": {
"DisplayPokemonList": true,
"MaxDistance": 1500.0,
"MaxEstimateTime": 600.0,
"CatchEmAllMinBalls": 50,
"TryCatchEmAll": true,
"CatchPokemonWhileWalking": true,
"SpinWhileWalking": true,
"AlwaysWalkback": false,
"SnipingScanOffset": 0.025,
"Enable": true,
"WalkbackDistanceLimit": 300.0
},

**Comment by samuraitruong** [comment]
yeah, I create a draft wiki here - https://github.com/NoxxDev/NecroBot/wiki/Human-walk-snipe-config

**Comment by Festum** [comment]
Thank you @samuraitruong . It's more human-liked.

**Comment by masterpowers** [comment]
@samuraitruong  , hi mate we should also save human sniping coordinates... that will be scanned...
which can be also human walk snipe... 
We can set up a human walking snipe to the default coordinate...
and to set of coordinates near your default coordinates...

Coz if you have discovered a nest you may want to keep on monitoring that area and walk to that area everytime the scan tells there is a pokemon there...

just another tweak for the human walk snipe...

**Comment by samuraitruong** [comment]
just change offset to bigger, that will cover all nest, because even you scan nest but if it too far, that useless because we don't have time to walk there. 

I going to introduce a feature that allow bot automatically adjust speed (with max speed configurable) to try catch the priority level pokemon, that should be fun

**Pull request merged**
