### PR TITLE
Fix for bug where lured Pokemons aren't caught when using GPX (#324)

### PR DESCRIPTION
**Pull request by mo0ojava**
## Description
Parent FarmPokestopsGPXTask (only) calls
        CatchNearbyPokemonsTask.Execute
        CatchIncensePokemonsTask.Execute
        UseNearbyPokestopsTask.Execute

Above happens while moving. Solution: check for lures in this module, and before doing
the other actions. The reason behind the bug could be cooldowns caused by the other tasks
leading to CatchLurePokemons not taking effect. This solution has been tested and works afaik.

+ also indented some other code here for better readability.

### CODE REVIEW

**Comment by tiggerite** [comment]
But the patch means the CatchLurePokemonsTask is now called twice - both before and inside FortPokestop. Also, this may cause issues with luring when not using GPX, because it no longer moves close enough to the stop to use it (and therefore lures may be too far away to capture).

The lures with GPX definitely worked before the FortPokestop function was added, but I can't see why that would have made a difference, because the code is still the same (bar the check for HumanWalkSniping)

**Comment by mo0ojava** [comment]
I may have missed something, but as far as I can see the only reference to CatchLurePokemons right now is the one included in the patch, ie in UseNearbyPokestops.Execute.
There *should* be no chance of that function being called twice...

FortPokestop seems designed to leave Lured Pokemons out with reference to FarmPokestopsGPXTask having it's own treatment of catching mobs.

**Comment by mo0ojava** [comment]
Also have to agree that something fishy is going on regarding CatchLurePokemons. It *should* work without the patch. But doesn't. The patch on the other hand is rather unobtrusive since it's only called when you have a lured Pokestop in sight. CatchLurePokemon then decides on distance etc.

**Comment by mo0ojava** [comment]
(Note that the patch removes the prior call to CatchLurePokemon)

**Comment by tiggerite** [comment]
I think it must be a cooldown issue. The code was an exact copy from FarmPokestopsTask, but there it's not checking every step, only when it reaches the next pokestop. I think probably the solution is to use something similar to the _lastTaskCall that used to be in FarmPokestopsGPXTask, with a Thread.Sleep for the remaining time before trying to CatchLurePokemon. I reckon the FortPokestop (should be FarmPokestop IMO) shouldn't really be calling CatchLurePokemon anyway though, as it's called at each intermediate pokestop for the HumanWalkSnipeTask, when really it should only be spinning those stops and trying to get to the snipe ASAP. So I do agree with you on that score.

**Comment by mo0ojava** [comment]
You're propably right regarding the cooldown. Until that part is properly solved I'd say the fix is an oksolution meanwhile. It only ever runs once per iteration in UseNearbyPokestops, and then only if the current Pokestop is lured. No other calls to that function takes place anywhere in the solution.

I've been running it since yesterday and it's working as intended:
```
[13:08:37.380] Looking for Pokemon...
[13:08:38.389] Looking for incense Pokemon...
[13:08:39.764] Looking for Pokemon...
[13:08:40.724] Looking for incense Pokemon...
[13:08:43.041] Looking for Pokemon...
[13:08:43.271] Looking for incense Pokemon...
[13:08:44.714] Looking for lure Pokemon...
[13:08:45.754] (Threw ball) Great hit. Curve-ball...
[13:08:47] (CatchSuccess) | (Lure) Pidgey Lvl: 2 CP: (24/30) IV: 25.00% | Chance: 100% | 22.51m dist | with a PokeBall (65 left). | 160 EXP earned | Candies: 3 | lat: X long: Y
[13:08:49] Name: Girl XP: 50, Gems: 0, Items: 2 x ItemPokeBall, 1 x ItemGreatBall, Lat: X, Long: Y
[13:08:50.029] Looking for Pokemon...
[13:08:50.244] Looking for incense Pokemon...
[13:08:52.408] Looking for Pokemon...
[13:08:52.638] Looking for incense Pokemon...
[13:08:54.721] Looking for Pokemon...
[13:08:54.958] Looking for incense Pokemon...
[13:08:57.440] Looking for Pokemon...
```

**Comment by tiggerite** [comment]
I've added a cooldown in #596 however it says there are conflicts. I can't see any, though?

**Pull request merged**
